language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install coveralls --use-mirrors
  - python setup.py install
# command to run tests
script:
  - coverage run --source=hieroglyph setup.py test
after_success:
  - coveralls
