language: python
python:
  - "2.7"
  - "3.4"

env:
  - SPHINX_SPEC=Sphinx~=1.2.0
  - SPHINX_SPEC=Sphinx~=1.3.0
  - SPHINX_SPEC=git+https://github.com/sphinx-doc/sphinx.git\#egg\=Sphinx-dev

before_install:
  - bundle install

install:
  - pip install coveralls
  - pip install $SPHINX_SPEC --allow-external Sphinx --allow-unverified Sphinx
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test
  - rake jasmine:ci JASMINE_CONFIG_PATH=./src/jstests/jasmine.yml
  - cd docs; READTHEDOCS=True SPHINXOPTS="-NqW" SPHINXBUILD="sphinx-build" make -e html slides

after_success:
  - coveralls
