cache: pip
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"

env:
  - SPHINX_SPEC='==1.4.0'
  - SPHINX_SPEC='==1.5.0'
  - SPHINX_SPEC='==1.6.1'
  - SPHINX_SPEC='==1.7.0'
  - SPHINX_SPEC='==1.8.0'
  - SPHINX_SPEC='==2.0.0'
  - SPHINX_SPEC=''

matrix:
  # exclude non Python2 compatible Sphinx versions
  exclude:
  - python: 2.7
    env: SPHINX_SPEC='==2.0.0'

install:
  - pip install coveralls sphinx_rtd_theme "sphinx${SPHINX_SPEC:-}"
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test
  - cd docs; READTHEDOCS=True SPHINXOPTS="-NqW" SPHINXBUILD="sphinx-build" make -e clean html slides

after_success:
  - coveralls
