language: python
python:
  - "2.7"
  - "3.3"

env:
  - SPHINX_VERSION=1.1.3
  - SPHINX_VERSION=1.2
  - SPHINX_VERSION=dev

install:
  - pip install coveralls --use-mirrors
  - pip install -q Sphinx==$SPHINX_VERSION --allow-external Sphinx --allow-unverified Sphinx
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test

after_success:
  - coveralls
