language: python
python:
  - "2.7"
  - "3.4"

env:
  - SPHINX_SPEC=Sphinx==1.1.3
  - SPHINX_SPEC=Sphinx==1.2.2
  - SPHINX_SPEC=http://bitbucket.org/birkenfeld/sphinx/get/tip.gz\#egg\Sphinx-dev

before_install:
  - bundle install

install:
  - pip install coveralls
  - pip install $SPHINX_SPEC --allow-external Sphinx --allow-unverified Sphinx
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test
  - rake jasmine:ci JASMINE_CONFIG_PATH=./src/jstests/jasmine.yml

after_success:
  - coveralls
